language: node_js
node_js:
  - "7"
services:
  - mongodb
env:
  - NODE_ENV=test
before_script:
  - npm install -g gulp-cli
script: npm test=
after_success:
  - npm run coverage
  - coveralls < coverage/lcov.info
